export const majorCategoryOptions = [
  {
    name: "공문을 통한 전공분야 대회참여",
    score: "25점",
    max_number: "최대 8회",
    send: "major-out_school_attendance-official_contest",
    id: 1,
  },
  {
    name: "전공분야 대회 개별참여",
    score: "25점",
    max_number: "최대 8회",
    send: "major-out_school_attendace-inofficial_contest",
    id: 1,
  },
  {
    name: "연합해커톤 참여",
    score: "25점",
    max_number: "최대 8회",
    send: "major-out_school_attendance-hackathon",
    id: 1,
  },
  {
    name: "전공 관련 교육프로그램 참여",
    score: "25점",
    max_number: "최대 8회",
    send: "major-out_school_attendance-seminar",
    id: 1,
  },
  {
    name: "GSM FESTIVAL 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "major-in_school_attendance-gsmfest",
    id: 2,
  },
  {
    name: "교내해커톤대회 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "major-in_school_attendance-hackathon",
    id: 2,
  },
  {
    name: "전공동아리 발표대회 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "major-in_school_attendance-club_presentation",
    id: 2,
  },
  {
    name: "전공특강(방과후) 참가",
    score: "15점",
    max_number: "최대 4회",
    send: "major-in_school_attendance-seminar",
    id: 3,
  },
  {
    name: "전공관련 방과후학교 이수",
    score: "45점",
    max_number: "최대 2회",
    send: "major-in_school_attendance-afterSchool",
    id: 4,
  },
];

export const humanCategoryOptions = [
  {
    name: "교내인성영역관련수상",
    score: "50점",
    max_number: "최대 4회",
    send: "humanities-award_career-humanity-in_school",
    id: 5,
  },
  {
    name: "교외인성영역관련수상",
    score: "50점",
    max_number: "최대 4회",
    send: "humanities-award_career-humanity-out_school",
    id: 5,
  },
  {
    name: "독서마라톤 거북이코스",
    score: "40점",
    send: "humanities-book-bookmarathon-turtle",
    id: 6,
  },
  {
    name: "독서마라톤 악어코스",
    score: "70점",
    send: "humanities-book-bookmarathon-crocodile",
    id: 6,
  },
  {
    name: "독서마라톤 토끼코스이상",
    score: "100점",
    send: "humanities-book-bookmarathon-over_rabbit",
    id: 6,
  },
  {
    name: "봉사활동",
    score: "시간당 5점",
    max_number: "최대 40시간",
    send: "humanities-service-activity",
    id: 8,
  },
  {
    name: "봉사동아리",
    score: "학기당 50점",
    max_number: "최대 2",
    send: "humanities-service-club",
    id: 9,
  },
  {
    name: "한자자격증",
    score: "50점 (4급 이상)",
    send: "humanities-certificate-chinese_character",
    id: 10,
  },
  {
    name: "한국사",
    score: "50점 (3급 이상)",
    send: "humanities-certificate-korean_history",
    id: 11,
  },
  {
    name: "자기주도적 활동",
    score: "25점",
    max_number: "최대 8회",
    send: "humanities-activities-self_directed_activities",
    id: 12,
  },
  {
    name: "뉴로우S",
    score: "5점 (1일 1회로 인정)",
    max_number: "최대 40",
    send: "humanities-activities-newrrow_s",
    id: 13,
  },
];

export const foreignCategoryOptions = [
  {
    name: "TOEIC 점수",
    score: "500점",
    send: "foreign_lang-test-toeic-score",
    id: 14,
  },
  {
    name: " TOEFL 점수",
    score: "500점",
    send: "foreign_lang-test-toefl-score",
    id: 14,
  },
  {
    name: "TEPS 점수",
    score: "500점",
    send: "foreign_lang-test-teps-score",
    id: 14,
  },
  {
    name: "TOEIC SPEAKING level",
    score: "500점",
    send: "foreign_lang-test-toeic_speaking-level",
    id: 14,
  },
  {
    name: "OPIC 등급",
    score: "500점",
    send: "foreign_lang-test-opic-grade",
    id: 14,
  },
  {
    name: "JPT 점수",
    score: "500점",
    send: "foreign_lang-test-jpt-score",
    id: 14,
  },
  {
    name: "CPT 점수",
    score: "500점",
    send: "foreign_lang-test-cpt-score",
    id: 14,
  },
  {
    name: "HSK 급수",
    score: "500점",
    send: "foreign_lang-test-hsk-grade",
    id: 14,
  },
  {
    name: "토사관 참여",
    score: "100점",
    send: "foreign_lang-attendance_toeic_academy-status",
    id: 15,
  },
];
