export const majorCategoryOptions = [
  {
    id: 1,
    name: "공문을 통한 전공분야 대회 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-OUT_SCHOOL-OFFICIAL",
  },
  {
    id: 1,
    name: "전공분야 대회 개별참여 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-OUT_SCHOOL-UNOFFICIAL",
  },
  {
    id: 1,
    name: "연합 해커톤 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-OUT_SCHOOL-HACKATHON",
  },
  {
    id: 2,
    name: "GSM FESTIVAL 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-IN_SCHOOL-GSMFEST",
  },
  {
    id: 2,
    name: "교내해커톤 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-IN_SCHOOL-SCHOOL_HACKATHON",
  },
  {
    id: 2,
    name: "전공동아리 발표 수상",
    score: "50점",
    max_number: "최대 6회",
    send: "MAJOR-AWARD_CAREER-IN_SCHOOL-PRESENTATION",
  },
  {
    id: 3,
    name: "전공(심화), 취업 동아리 참여 - 1학기",
    score: "50점",
    max_number: "최대 2회",
    send: "MAJOR-CLUB_ATTENDANCE_SEMESTER_1",
  },
  {
    id: 3,
    name: "전공(심화), 취업 동아리 참여 - 2학기",
    score: "50점",
    max_number: "최대 2회",
    send: "MAJOR-CLUB_ATTENDANCE_SEMESTER_2",
  },
  {
    id: 4,
    name: "공문을 통한 전공분야 대회 참가",
    score: "25점",
    max_number: "최대 8회",
    send: "MAJOR-OUT_SCHOOL-ATTENDANCE_OFFICIAL_CONTEST",
  },
  {
    id: 4,
    name: "전공분야 대회 개별참여 참가",
    score: "25점",
    max_number: "최대 8회",
    send: "MAJOR-OUT_SCHOOL-ATTENDANCE_UNOFFICIAL_CONTEST",
  },
  {
    id: 4,
    name: "연합 해커톤 참가",
    score: "25점",
    max_number: "최대 8회",
    send: "MAJOR-OUT_SCHOOL-ATTENDANCE_HACKATHON",
  },
  {
    id: 4,
    name: "전공 관련 교육 프로그램(세미나 등) 참가",
    score: "25점",
    max_number: "최대 8회",
    send: "MAJOR-OUT_SCHOOL-ATTENDANCE_SEMINAR",
  },
  {
    id: 5,
    name: "GSM FESTIVAL 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "MAJOR-IN_SCHOOL-ATTENDANCE_GSMFEST",
  },
  {
    id: 5,
    name: "교내 해커톤 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "MAJOR-IN_SCHOOL-ATTENDANCE_HACKATHON",
  },
  {
    id: 5,
    name: "전공동아리 발표대회 참가",
    score: "50점",
    max_number: "최대 3회",
    send: "MAJOR-IN_SCHOOL-ATTENDANCE_CLUB-PRESENTATION",
  },
  {
    id: 6,
    name: "전공특강(방과후) 참가",
    score: "15점",
    max_number: "최대 4회",
    send: "MAJOR-IN_SCHOOL-ATTENDANCE_SEMINAR",
  },
  {
    id: 7,
    name: "전공 관련 방과후학교 이수",
    score: "45점",
    max_number: "최대 2회",
    send: "MAJOR-IN_SCHOOL-ATTENDANCE_AFTER-SCHOOL",
  },
];

export const humanCategoryOptions = [
  {
    name: "교내인성영역관련수상",
    score: "50점",
    max_number: "최대 4회",
    send: "HUMANITIES-AWARD_CAREER-HUMANITY-IN_SCHOOL",
    id: 5,
  },
  {
    name: "교외인성영역관련수상",
    score: "50점",
    max_number: "최대 4회",
    send: "HUMANITIES-AWARD_CAREER-HUMANITY-OUT_SCHOOL",
    id: 5,
  },
  {
    name: "독서마라톤 거북이코스",
    score: "40점",
    send: "HUMANITIES-BOOK-BOOKMARATHON-TURTLE",
    id: 6,
  },
  {
    name: "독서마라톤 악어코스",
    score: "70점",
    send: "HUMANITIES-BOOK-BOOKMARATHON-CROCODILE",
    id: 6,
  },
  {
    name: "독서마라톤 토끼코스이상",
    score: "100점",
    send: "HUMANITIES-BOOK-BOOKMARATHON-OVER_RABBIT",
    id: 6,
  },
  {
    name: "봉사활동",
    score: "시간당 5점",
    max_number: "최대 40시간",
    send: "HUMANITIES-SERVICE-ACTIVITY",
    id: 8,
  },
  {
    name: "봉사동아리",
    score: "학기당 50점",
    max_number: "최대 2",
    send: "HUMANITIES-SERVICE-CLUB",
    id: 9,
  },
  {
    name: "한자자격증",
    score: "50점 (4급 이상)",
    send: "HUMANITIES-CERTIFICATE-CHINESE_CHARACTER",
    id: 10,
  },
  {
    name: "한국사",
    score: "50점 (3급 이상)",
    send: "HUMANITIES-CERTIFICATE-KOREAN_HISTORY",
    id: 11,
  },
  {
    name: "자기주도적 활동",
    score: "25점",
    max_number: "최대 8회",
    send: "HUMANITIES-ACTIVITIES-SELF_DIRECTED_ACTIVITIES",
    id: 12,
  },
  {
    name: "뉴로우S",
    score: "5점 (1일 1회로 인정)",
    max_number: "최대 40",
    send: "HUMANITIES-ACTIVITIES-NEWRROW_S",
    id: 13,
  },
];

export const foreignCategoryOptions = [
  {
    name: "TOEIC 점수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-TOEIC-SCORE",
    id: 14,
  },
  {
    name: "TOEFL 점수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-TOEFL-SCORE",
    id: 14,
  },
  {
    name: "TEPS 점수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-TEPS-SCORE",
    id: 14,
  },
  {
    name: "TOEIC SPEAKING level",
    score: "500점",
    send: "FOREIGN_LANG-TEST-TOEIC_SPEAKING-LEVEL",
    id: 14,
  },
  {
    name: "OPIC 등급",
    score: "500점",
    send: "FOREIGN_LANG-TEST-OPIC-GRADE",
    id: 14,
  },
  {
    name: "JPT 점수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-JPT-SCORE",
    id: 14,
  },
  {
    name: "CPT 점수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-CPT-SCORE",
    id: 14,
  },
  {
    name: "HSK 급수",
    score: "500점",
    send: "FOREIGN_LANG-TEST-HSK-GRADE",
    id: 14,
  },
  {
    name: "토사관 참여",
    score: "100점",
    send: "FOREIGN_LANG-ATTENDANCE_TOEIC_ACADEMY-STATUS",
    id: 15,
  },
];
