export const SCORE_CATEGORIES = {
  ACTIVITY: "HUMANITIES-SERVICE-ACTIVITY",
  SEMESTER_1: "HUMANITIES-SERVICE-CLUB_SEMESTER_1",
  SEMESTER_2: "HUMANITIES-SERVICE-CLUB_SEMESTER_2",
  NEWRROW: "HUMANITIES-ACTIVITIES-NEWRROW_S",
  TOEIC: "FOREIGN_LANG-ATTENDANCE-TOEIC_ACADEMY_STATUS",
};
